// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=null.  DO NOT EDIT!
#pragma warning disable
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace org.zhangqi.proto {
  
  public static partial class LocalServer {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Extensions
    internal static readonly object Descriptor;
    static LocalServer() {
      Descriptor = null;
    }
    #endregion
    
  }
  #region Enums
  public enum LocalRpcNameEnum {
    LocalRpcRegistToGmServer = 300001,
    LocalRpcLogicServerMatch = 310001,
    LocalRpcBattleServerInitBattle = 320001,
  }
  
  #endregion
  
}

#endregion Designer generated code
#pragma warning restore
