// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_server.proto

package org.zhangqi.proto;

public final class LocalServer {
  private LocalServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.zhangqi.proto.LocalRpcNameEnum}
   *
   * <pre>
   * 服务器内部通信协议名
   * </pre>
   */
  public enum LocalRpcNameEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LocalRpcRegistToGmServer = 300001;</code>
     *
     * <pre>
     * 向GM服务器注册
     * </pre>
     */
    LocalRpcRegistToGmServer(0, 300001),
    /**
     * <code>LocalRpcLogicServerMatch = 310001;</code>
     *
     * <pre>
     * logicServer循环通知自己进行匹配计算
     * </pre>
     */
    LocalRpcLogicServerMatch(1, 310001),
    /**
     * <code>LocalRpcBattleServerInitBattle = 320001;</code>
     *
     * <pre>
     * battleServer通知初始化战斗
     * </pre>
     */
    LocalRpcBattleServerInitBattle(2, 320001),
    ;

    /**
     * <code>LocalRpcRegistToGmServer = 300001;</code>
     *
     * <pre>
     * 向GM服务器注册
     * </pre>
     */
    public static final int LocalRpcRegistToGmServer_VALUE = 300001;
    /**
     * <code>LocalRpcLogicServerMatch = 310001;</code>
     *
     * <pre>
     * logicServer循环通知自己进行匹配计算
     * </pre>
     */
    public static final int LocalRpcLogicServerMatch_VALUE = 310001;
    /**
     * <code>LocalRpcBattleServerInitBattle = 320001;</code>
     *
     * <pre>
     * battleServer通知初始化战斗
     * </pre>
     */
    public static final int LocalRpcBattleServerInitBattle_VALUE = 320001;


    public final int getNumber() { return value; }

    public static LocalRpcNameEnum valueOf(int value) {
      switch (value) {
        case 300001: return LocalRpcRegistToGmServer;
        case 310001: return LocalRpcLogicServerMatch;
        case 320001: return LocalRpcBattleServerInitBattle;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LocalRpcNameEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LocalRpcNameEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LocalRpcNameEnum>() {
            public LocalRpcNameEnum findValueByNumber(int number) {
              return LocalRpcNameEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.zhangqi.proto.LocalServer.getDescriptor().getEnumTypes().get(0);
    }

    private static final LocalRpcNameEnum[] VALUES = values();

    public static LocalRpcNameEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LocalRpcNameEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.zhangqi.proto.LocalRpcNameEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022local_server.proto\022\021org.zhangqi.proto*" +
      "x\n\020LocalRpcNameEnum\022\036\n\030LocalRpcRegistToG" +
      "mServer\020\341\247\022\022\036\n\030LocalRpcLogicServerMatch\020" +
      "\361\365\022\022$\n\036LocalRpcBattleServerInitBattle\020\201\304" +
      "\023B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
