// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.zhangqi.proto;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.zhangqi.proto.RpcNameEnum}
   *
   * <pre>
   * 客户端与服务器通讯协议名
   * </pre>
   */
  public enum RpcNameEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Regist = 101;</code>
     *
     * <pre>
     * 注册
     * </pre>
     */
    Regist(0, 101),
    /**
     * <code>Login = 102;</code>
     *
     * <pre>
     * 登录
     * </pre>
     */
    Login(1, 102),
    /**
     * <code>Match = 111;</code>
     *
     * <pre>
     * 对战匹配
     * </pre>
     */
    Match(2, 111),
    /**
     * <code>CancelMatch = 112;</code>
     *
     * <pre>
     * 取消对战匹配
     * </pre>
     */
    CancelMatch(3, 112),
    /**
     * <code>GetBattleInfo = 6001;</code>
     *
     * <pre>
     * ------------- 对战相关 -------------
     * </pre>
     */
    GetBattleInfo(4, 6001),
    /**
     * <code>Concede = 6002;</code>
     *
     * <pre>
     * 投降认输
     * </pre>
     */
    Concede(5, 6002),
    /**
     * <code>PlacePieces = 6003;</code>
     *
     * <pre>
     * 落子
     * </pre>
     */
    PlacePieces(6, 6003),
    /**
     * <code>ForceEndTurn = 6004;</code>
     *
     * <pre>
     * 客户端发现当前回合玩家超时未行动，请求服务器强制结束回合
     * </pre>
     */
    ForceEndTurn(7, 6004),
    /**
     * <code>ReadyToStartGame = 6005;</code>
     *
     * <pre>
     * 确认可以开始游戏
     * </pre>
     */
    ReadyToStartGame(8, 6005),
    /**
     * <code>ForceReadyToStartGame = 6006;</code>
     *
     * <pre>
     * 超时未确认可以开始游戏，则强制开始游戏
     * </pre>
     */
    ForceReadyToStartGame(9, 6006),
    /**
     * <code>ForceOfflinePush = 20001;</code>
     *
     * <pre>
     * ------------- 服务器推送 -------------
     * </pre>
     */
    ForceOfflinePush(10, 20001),
    /**
     * <code>MatchResultPush = 21001;</code>
     *
     * <pre>
     * 主逻辑服务器推送给玩家匹配结果
     * </pre>
     */
    MatchResultPush(11, 21001),
    /**
     * <code>BattleEventMsgListPush = 22001;</code>
     *
     * <pre>
     * 战斗服务器推送给玩家场上发生的事件信息
     * </pre>
     */
    BattleEventMsgListPush(12, 22001),
    ;

    /**
     * <code>Regist = 101;</code>
     *
     * <pre>
     * 注册
     * </pre>
     */
    public static final int Regist_VALUE = 101;
    /**
     * <code>Login = 102;</code>
     *
     * <pre>
     * 登录
     * </pre>
     */
    public static final int Login_VALUE = 102;
    /**
     * <code>Match = 111;</code>
     *
     * <pre>
     * 对战匹配
     * </pre>
     */
    public static final int Match_VALUE = 111;
    /**
     * <code>CancelMatch = 112;</code>
     *
     * <pre>
     * 取消对战匹配
     * </pre>
     */
    public static final int CancelMatch_VALUE = 112;
    /**
     * <code>GetBattleInfo = 6001;</code>
     *
     * <pre>
     * ------------- 对战相关 -------------
     * </pre>
     */
    public static final int GetBattleInfo_VALUE = 6001;
    /**
     * <code>Concede = 6002;</code>
     *
     * <pre>
     * 投降认输
     * </pre>
     */
    public static final int Concede_VALUE = 6002;
    /**
     * <code>PlacePieces = 6003;</code>
     *
     * <pre>
     * 落子
     * </pre>
     */
    public static final int PlacePieces_VALUE = 6003;
    /**
     * <code>ForceEndTurn = 6004;</code>
     *
     * <pre>
     * 客户端发现当前回合玩家超时未行动，请求服务器强制结束回合
     * </pre>
     */
    public static final int ForceEndTurn_VALUE = 6004;
    /**
     * <code>ReadyToStartGame = 6005;</code>
     *
     * <pre>
     * 确认可以开始游戏
     * </pre>
     */
    public static final int ReadyToStartGame_VALUE = 6005;
    /**
     * <code>ForceReadyToStartGame = 6006;</code>
     *
     * <pre>
     * 超时未确认可以开始游戏，则强制开始游戏
     * </pre>
     */
    public static final int ForceReadyToStartGame_VALUE = 6006;
    /**
     * <code>ForceOfflinePush = 20001;</code>
     *
     * <pre>
     * ------------- 服务器推送 -------------
     * </pre>
     */
    public static final int ForceOfflinePush_VALUE = 20001;
    /**
     * <code>MatchResultPush = 21001;</code>
     *
     * <pre>
     * 主逻辑服务器推送给玩家匹配结果
     * </pre>
     */
    public static final int MatchResultPush_VALUE = 21001;
    /**
     * <code>BattleEventMsgListPush = 22001;</code>
     *
     * <pre>
     * 战斗服务器推送给玩家场上发生的事件信息
     * </pre>
     */
    public static final int BattleEventMsgListPush_VALUE = 22001;


    public final int getNumber() { return value; }

    public static RpcNameEnum valueOf(int value) {
      switch (value) {
        case 101: return Regist;
        case 102: return Login;
        case 111: return Match;
        case 112: return CancelMatch;
        case 6001: return GetBattleInfo;
        case 6002: return Concede;
        case 6003: return PlacePieces;
        case 6004: return ForceEndTurn;
        case 6005: return ReadyToStartGame;
        case 6006: return ForceReadyToStartGame;
        case 20001: return ForceOfflinePush;
        case 21001: return MatchResultPush;
        case 22001: return BattleEventMsgListPush;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RpcNameEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RpcNameEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RpcNameEnum>() {
            public RpcNameEnum findValueByNumber(int number) {
              return RpcNameEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.zhangqi.proto.Rpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final RpcNameEnum[] VALUES = values();

    public static RpcNameEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RpcNameEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.zhangqi.proto.RpcNameEnum)
  }

  /**
   * Protobuf enum {@code org.zhangqi.proto.RpcErrorCodeEnum}
   *
   * <pre>
   * 客户端与服务器通讯协议错误码
   * </pre>
   */
  public enum RpcErrorCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Ok = 0;</code>
     *
     * <pre>
     * 正常
     * </pre>
     */
    Ok(0, 0),
    /**
     * <code>ServerError = 1;</code>
     *
     * <pre>
     * 服务器内部错误
     * </pre>
     */
    ServerError(1, 1),
    /**
     * <code>ClientError = 2;</code>
     *
     * <pre>
     * 客户端请求参数非法
     * </pre>
     */
    ClientError(2, 2),
    /**
     * <code>ServerNotAvailable = 3;</code>
     *
     * <pre>
     * 服务器当前不可用
     * </pre>
     */
    ServerNotAvailable(3, 3),
    /**
     * <code>UserNotInBattle = 11;</code>
     *
     * <pre>
     * 玩家不在对战中
     * </pre>
     */
    UserNotInBattle(4, 11),
    /**
     * <code>BattleNotStart = 12;</code>
     *
     * <pre>
     * 游戏尚未开始（需双方都确认ReadyToStartGame）
     * </pre>
     */
    BattleNotStart(5, 12),
    /**
     * <code>IsNotUserTurn = 13;</code>
     *
     * <pre>
     * 不是该玩家的回合
     * </pre>
     */
    IsNotUserTurn(6, 13),
    /**
     * <code>InputLastEventNumError = 14;</code>
     *
     * <pre>
     * 客户端请求对战操作时附带的lastEventNum错误，说明发生丢包
     * </pre>
     */
    InputLastEventNumError(7, 14),
    /**
     * <code>RegisErrorUsernameIsExist = 1011;</code>
     *
     * <pre>
     * 无法注册，用户名已存在
     * </pre>
     */
    RegisErrorUsernameIsExist(8, 1011),
    /**
     * <code>RegisErrorUsernameIllegal = 1012;</code>
     *
     * <pre>
     * 无法注册，用户名非法
     * </pre>
     */
    RegisErrorUsernameIllegal(9, 1012),
    /**
     * <code>RegisErrorPasswordIllegal = 1013;</code>
     *
     * <pre>
     * 无法注册，密码非法
     * </pre>
     */
    RegisErrorPasswordIllegal(10, 1013),
    /**
     * <code>LoginErrorUsernameIsNotExist = 1021;</code>
     *
     * <pre>
     * 无法登录，用户名不存在
     * </pre>
     */
    LoginErrorUsernameIsNotExist(11, 1021),
    /**
     * <code>LoginErrorPasswordWrong = 1022;</code>
     *
     * <pre>
     * 无法登录，密码错误
     * </pre>
     */
    LoginErrorPasswordWrong(12, 1022),
    /**
     * <code>LoginErrorForbid = 1023;</code>
     *
     * <pre>
     * 无法登录，账号被封禁
     * </pre>
     */
    LoginErrorForbid(13, 1023),
    /**
     * <code>MatchErrorMatching = 1111;</code>
     *
     * <pre>
     * 无法匹配，目前就是匹配状态
     * </pre>
     */
    MatchErrorMatching(14, 1111),
    /**
     * <code>MatchErrorPlaying = 1112;</code>
     *
     * <pre>
     * 无法匹配，已经在对战中
     * </pre>
     */
    MatchErrorPlaying(15, 1112),
    /**
     * <code>MatchErrorOtherActionState = 1113;</code>
     *
     * <pre>
     * 无法匹配，处于其他状态
     * </pre>
     */
    MatchErrorOtherActionState(16, 1113),
    /**
     * <code>CancelMatchErrorPlaying = 1121;</code>
     *
     * <pre>
     * 取消匹配失败，已经在对战中
     * </pre>
     */
    CancelMatchErrorPlaying(17, 1121),
    /**
     * <code>CancelMatchErrorNotMatching = 1122;</code>
     *
     * <pre>
     * 取消匹配失败，没有在匹配中
     * </pre>
     */
    CancelMatchErrorNotMatching(18, 1122),
    /**
     * <code>PlacePiecesErrorIndexError = 60031;</code>
     *
     * <pre>
     * 请求落子错误，要落子的位置非法
     * </pre>
     */
    PlacePiecesErrorIndexError(19, 60031),
    /**
     * <code>PlacePiecesErrorIndexIsNotEmpty = 60032;</code>
     *
     * <pre>
     * 请求落子错误，要落子的位置已经有棋子
     * </pre>
     */
    PlacePiecesErrorIndexIsNotEmpty(20, 60032),
    /**
     * <code>ReadyToStartGameErrorAlreadyReady = 60051;</code>
     *
     * <pre>
     * 确认可以开始游戏错误，已经确认过了
     * </pre>
     */
    ReadyToStartGameErrorAlreadyReady(21, 60051),
    /**
     * <code>ForceReadyToStartGameErrorAlreadyStart = 60052;</code>
     *
     * <pre>
     * 请求强制开始游戏错误，游戏已经开始了
     * </pre>
     */
    ForceReadyToStartGameErrorAlreadyStart(22, 60052),
    ;

    /**
     * <code>Ok = 0;</code>
     *
     * <pre>
     * 正常
     * </pre>
     */
    public static final int Ok_VALUE = 0;
    /**
     * <code>ServerError = 1;</code>
     *
     * <pre>
     * 服务器内部错误
     * </pre>
     */
    public static final int ServerError_VALUE = 1;
    /**
     * <code>ClientError = 2;</code>
     *
     * <pre>
     * 客户端请求参数非法
     * </pre>
     */
    public static final int ClientError_VALUE = 2;
    /**
     * <code>ServerNotAvailable = 3;</code>
     *
     * <pre>
     * 服务器当前不可用
     * </pre>
     */
    public static final int ServerNotAvailable_VALUE = 3;
    /**
     * <code>UserNotInBattle = 11;</code>
     *
     * <pre>
     * 玩家不在对战中
     * </pre>
     */
    public static final int UserNotInBattle_VALUE = 11;
    /**
     * <code>BattleNotStart = 12;</code>
     *
     * <pre>
     * 游戏尚未开始（需双方都确认ReadyToStartGame）
     * </pre>
     */
    public static final int BattleNotStart_VALUE = 12;
    /**
     * <code>IsNotUserTurn = 13;</code>
     *
     * <pre>
     * 不是该玩家的回合
     * </pre>
     */
    public static final int IsNotUserTurn_VALUE = 13;
    /**
     * <code>InputLastEventNumError = 14;</code>
     *
     * <pre>
     * 客户端请求对战操作时附带的lastEventNum错误，说明发生丢包
     * </pre>
     */
    public static final int InputLastEventNumError_VALUE = 14;
    /**
     * <code>RegisErrorUsernameIsExist = 1011;</code>
     *
     * <pre>
     * 无法注册，用户名已存在
     * </pre>
     */
    public static final int RegisErrorUsernameIsExist_VALUE = 1011;
    /**
     * <code>RegisErrorUsernameIllegal = 1012;</code>
     *
     * <pre>
     * 无法注册，用户名非法
     * </pre>
     */
    public static final int RegisErrorUsernameIllegal_VALUE = 1012;
    /**
     * <code>RegisErrorPasswordIllegal = 1013;</code>
     *
     * <pre>
     * 无法注册，密码非法
     * </pre>
     */
    public static final int RegisErrorPasswordIllegal_VALUE = 1013;
    /**
     * <code>LoginErrorUsernameIsNotExist = 1021;</code>
     *
     * <pre>
     * 无法登录，用户名不存在
     * </pre>
     */
    public static final int LoginErrorUsernameIsNotExist_VALUE = 1021;
    /**
     * <code>LoginErrorPasswordWrong = 1022;</code>
     *
     * <pre>
     * 无法登录，密码错误
     * </pre>
     */
    public static final int LoginErrorPasswordWrong_VALUE = 1022;
    /**
     * <code>LoginErrorForbid = 1023;</code>
     *
     * <pre>
     * 无法登录，账号被封禁
     * </pre>
     */
    public static final int LoginErrorForbid_VALUE = 1023;
    /**
     * <code>MatchErrorMatching = 1111;</code>
     *
     * <pre>
     * 无法匹配，目前就是匹配状态
     * </pre>
     */
    public static final int MatchErrorMatching_VALUE = 1111;
    /**
     * <code>MatchErrorPlaying = 1112;</code>
     *
     * <pre>
     * 无法匹配，已经在对战中
     * </pre>
     */
    public static final int MatchErrorPlaying_VALUE = 1112;
    /**
     * <code>MatchErrorOtherActionState = 1113;</code>
     *
     * <pre>
     * 无法匹配，处于其他状态
     * </pre>
     */
    public static final int MatchErrorOtherActionState_VALUE = 1113;
    /**
     * <code>CancelMatchErrorPlaying = 1121;</code>
     *
     * <pre>
     * 取消匹配失败，已经在对战中
     * </pre>
     */
    public static final int CancelMatchErrorPlaying_VALUE = 1121;
    /**
     * <code>CancelMatchErrorNotMatching = 1122;</code>
     *
     * <pre>
     * 取消匹配失败，没有在匹配中
     * </pre>
     */
    public static final int CancelMatchErrorNotMatching_VALUE = 1122;
    /**
     * <code>PlacePiecesErrorIndexError = 60031;</code>
     *
     * <pre>
     * 请求落子错误，要落子的位置非法
     * </pre>
     */
    public static final int PlacePiecesErrorIndexError_VALUE = 60031;
    /**
     * <code>PlacePiecesErrorIndexIsNotEmpty = 60032;</code>
     *
     * <pre>
     * 请求落子错误，要落子的位置已经有棋子
     * </pre>
     */
    public static final int PlacePiecesErrorIndexIsNotEmpty_VALUE = 60032;
    /**
     * <code>ReadyToStartGameErrorAlreadyReady = 60051;</code>
     *
     * <pre>
     * 确认可以开始游戏错误，已经确认过了
     * </pre>
     */
    public static final int ReadyToStartGameErrorAlreadyReady_VALUE = 60051;
    /**
     * <code>ForceReadyToStartGameErrorAlreadyStart = 60052;</code>
     *
     * <pre>
     * 请求强制开始游戏错误，游戏已经开始了
     * </pre>
     */
    public static final int ForceReadyToStartGameErrorAlreadyStart_VALUE = 60052;


    public final int getNumber() { return value; }

    public static RpcErrorCodeEnum valueOf(int value) {
      switch (value) {
        case 0: return Ok;
        case 1: return ServerError;
        case 2: return ClientError;
        case 3: return ServerNotAvailable;
        case 11: return UserNotInBattle;
        case 12: return BattleNotStart;
        case 13: return IsNotUserTurn;
        case 14: return InputLastEventNumError;
        case 1011: return RegisErrorUsernameIsExist;
        case 1012: return RegisErrorUsernameIllegal;
        case 1013: return RegisErrorPasswordIllegal;
        case 1021: return LoginErrorUsernameIsNotExist;
        case 1022: return LoginErrorPasswordWrong;
        case 1023: return LoginErrorForbid;
        case 1111: return MatchErrorMatching;
        case 1112: return MatchErrorPlaying;
        case 1113: return MatchErrorOtherActionState;
        case 1121: return CancelMatchErrorPlaying;
        case 1122: return CancelMatchErrorNotMatching;
        case 60031: return PlacePiecesErrorIndexError;
        case 60032: return PlacePiecesErrorIndexIsNotEmpty;
        case 60051: return ReadyToStartGameErrorAlreadyReady;
        case 60052: return ForceReadyToStartGameErrorAlreadyStart;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RpcErrorCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RpcErrorCodeEnum>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RpcErrorCodeEnum>() {
            public RpcErrorCodeEnum findValueByNumber(int number) {
              return RpcErrorCodeEnum.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.zhangqi.proto.Rpc.getDescriptor().getEnumTypes().get(1);
    }

    private static final RpcErrorCodeEnum[] VALUES = values();

    public static RpcErrorCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RpcErrorCodeEnum(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.zhangqi.proto.RpcErrorCodeEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\021org.zhangqi.proto*\207\002\n\013RpcNa" +
      "meEnum\022\n\n\006Regist\020e\022\t\n\005Login\020f\022\t\n\005Match\020o" +
      "\022\017\n\013CancelMatch\020p\022\022\n\rGetBattleInfo\020\361.\022\014\n" +
      "\007Concede\020\362.\022\020\n\013PlacePieces\020\363.\022\021\n\014ForceEn" +
      "dTurn\020\364.\022\025\n\020ReadyToStartGame\020\365.\022\032\n\025Force" +
      "ReadyToStartGame\020\366.\022\026\n\020ForceOfflinePush\020" +
      "\241\234\001\022\025\n\017MatchResultPush\020\211\244\001\022\034\n\026BattleEven" +
      "tMsgListPush\020\361\253\001*\226\005\n\020RpcErrorCodeEnum\022\006\n" +
      "\002Ok\020\000\022\017\n\013ServerError\020\001\022\017\n\013ClientError\020\002\022" +
      "\026\n\022ServerNotAvailable\020\003\022\023\n\017UserNotInBatt",
      "le\020\013\022\022\n\016BattleNotStart\020\014\022\021\n\rIsNotUserTur" +
      "n\020\r\022\032\n\026InputLastEventNumError\020\016\022\036\n\031Regis" +
      "ErrorUsernameIsExist\020\363\007\022\036\n\031RegisErrorUse" +
      "rnameIllegal\020\364\007\022\036\n\031RegisErrorPasswordIll" +
      "egal\020\365\007\022!\n\034LoginErrorUsernameIsNotExist\020" +
      "\375\007\022\034\n\027LoginErrorPasswordWrong\020\376\007\022\025\n\020Logi" +
      "nErrorForbid\020\377\007\022\027\n\022MatchErrorMatching\020\327\010" +
      "\022\026\n\021MatchErrorPlaying\020\330\010\022\037\n\032MatchErrorOt" +
      "herActionState\020\331\010\022\034\n\027CancelMatchErrorPla" +
      "ying\020\341\010\022 \n\033CancelMatchErrorNotMatching\020\342",
      "\010\022 \n\032PlacePiecesErrorIndexError\020\377\324\003\022%\n\037P" +
      "lacePiecesErrorIndexIsNotEmpty\020\200\325\003\022\'\n!Re" +
      "adyToStartGameErrorAlreadyReady\020\223\325\003\022,\n&F" +
      "orceReadyToStartGameErrorAlreadyStart\020\224\325" +
      "\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
